server:
  port: 8083

spring:
  datasource:
    url: jdbc:sqlite:data/zookeeper_admin.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
      defer-datasource-initialization: true
  sql:
    init:
      mode: always
default:
  # ?????????
  username: admin
  # ?????????
  password: admin
